import './globals.css'

import Nav from '@/app/components/molecules/nav'



export const metadata = {
  title: 'Financial Tool ',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Nav />
        {children}
        </body>
    </html>
  )
}
